export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';

export const MOVIES_FAILURE = 'CONTENT.MOVIES_FAILURE';
export const MOVIES_SUCESS = 'CONTENT.MOVIES_SUCESS';
export const MOVIES_REQ = 'CONTENT.MOVIES_REQ';

export const MOVIE_FAILURE = 'CONTENT.MOVIE_FAILURE';
export const MOVIE_SUCESS = 'CONTENT.MOVIE_SUCESS';
export const MOVIE_REQ = 'CONTENT.MOVIE_REQ';
