export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';
export const ADD_STORE_MOVIES = 'CONTENT.ADD_STORE_MOVIES';
export const SET_STORE_MOVIES_SOURCE = 'CONTENT.SET_STORE_MOVIES_SOURCE';

export const MOVIES_FAILURE = 'CONTENT.MOVIES_FAILURE';
export const MOVIES_SUCESS = 'CONTENT.MOVIES_SUCESS';
export const MOVIES_REQ = 'CONTENT.MOVIES_REQUEST';

// export const MOVIES_FAILURE = 'CONTENT.MOVIES_FAILURE';
// export const MOVIES_SUCESS = 'CONTENT.MOVIES_SUCESS';
// export const MOVIES_REQ = 'CONTENT.MOVIES_REQUEST';
