export const ADD_FAVORITE = 'CONTENT.ADD_FAVORITE';
export const REMOVE_FAVORITE = 'CONTENT.REMOVE_FAVORITE';
export const ADD_STORE_MOVIES = 'CONTENT.ADD_STORE_MOVIES';
export const SET_STORE_MOVIES_SOURCE = 'CONTENT.SET_STORE_MOVIES_SOURCE';
